### ISSUE TITLE
[[: not found Errors

### ISSUE THREAD

**Issue by c3x** [flyser/html5video#1]
Hello!
Nice script and that, I'm looking for since a long time.

I try to use it, but I get errors, when I try to run this script.

root@dedi-fr-41137:# ./html5video.sh m287554.mp4
./html5video.sh: 5: ./html5video.sh: [[: not found
./html5video.sh: 11: ./html5video.sh: [[: not found
./html5video.sh: 16: ./html5video.sh: [[: not found
ffmpeg version N-74791-g95010d4 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/root/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'm287554.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2015-09-04 15:20:24
  Duration: 00:00:24.06, start: 0.000000, bitrate: 10321 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 10011 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2015-09-04 15:20:24
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2015-09-04 15:20:24
      handler_name    : Alias Data Handler
Output #0, image2, to 'poster-T9rWzxP3W.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf56.40.101
    Stream #0:0(eng): Video: png, rgb24, 1280x720, q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2015-09-04 15:20:24
      handler_name    : Alias Data Handler
      encoder         : Lavc56.60.100 png
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A
video:785kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
./html5video.sh: 30: ./html5video.sh: [[: not found
(Many times the same error message)
./html5video.sh: 32: ./html5video.sh: [[: not found
-e poster.jpeg: size=230400     quality=10      filesize=4
./html5video.sh: 49: ./html5video.sh: [[: not found
./html5video.sh: 52: ./html5video.sh: Bad substitution

FFMPEG is working fine. When I start the commands

rm -f ffmpeg2pass*
ffmpeg -y  -i "286971.mp4" -threads 0 -c:v libx264 -pix_fmt yuv420p -profile:v "baseline" -preset veryslow -b:v "384k" -pass 1 -c:a libfdk_aac -b:a "96k" -vf "scale=trunc(426/2)_2:trunc(240/2)_2" -f mp4  /dev/null
ffmpeg     -i "286971.mp4" -threads 0 -movflags +faststart -c:v libx264 -pix_fmt yuv420p -profile:v "baseline" -preset veryslow -b:v "384k" -pass 2 -c:a libfdk_aac -b:a "96k" -vf "scale=trunc(426/2)_2:trunc(240/2)_2" "286971_240p.mp4"
rm -f ffmpeg2pass*
ffmpeg -y  -i "286971.mp4" -threads 0 -c:v libx264 -pix_fmt yuv420p -profile:v "baseline" -preset veryslow -b:v "768k" -pass 1 -c:a libfdk_aac -b:a "128k" -vf "scale=trunc(640/2)_2:trunc(360/2)_2" -f mp4  /dev/null
ffmpeg     -i "286971.mp4" -threads 0 -movflags +faststart -c:v libx264 -pix_fmt yuv420p -profile:v "baseline" -preset veryslow -b:v "768k" -pass 2 -c:a libfdk_aac -b:a "128k" -vf "scale=trunc(640/2)_2:trunc(360/2)_2" "286971_360p.mp4"
rm -f ffmpeg2pass*
ffmpeg -y  -i "286971.mp4" -threads 0 -c:v libx264 -pix_fmt yuv420p -profile:v "main" -preset veryslow -b:v "1536k" -pass 1 -c:a libfdk_aac -b:a "128k" -vf "scale=trunc(854/2)_2:trunc(480/2)_2" -f mp4  /dev/null
ffmpeg     -i "286971.mp4" -threads 0 -movflags +faststart -c:v libx264 -pix_fmt yuv420p -profile:v "main" -preset veryslow -b:v "1536k" -pass 2 -c:a libfdk_aac -b:a "128k" -vf "scale=trunc(854/2)_2:trunc(480/2)_2" "286971_480p.mp4"
rm -f ffmpeg2pass*

ffmpeg -i "286971.mp4" -threads 0 -c:v vp9 -c:a libopus -b:a "96k"  -vbr on -compression_level 10 -pix_fmt yuv420p -quality good -b:v "384k"  -crf 4 -vf "scale=trunc(426/2)_2:trunc(240/2)_2" -strict -2  "286971_240p.webm"
ffmpeg -i "286971.mp4" -threads 0 -c:v vp9 -c:a libopus -b:a "128k" -vbr on -compression_level 10 -pix_fmt yuv420p -quality good -b:v "512k"  -crf 4 -vf "scale=trunc(360/2)_2:trunc(640/2)_2" -strict -2  "286971_360p.webm"
ffmpeg -i "286971.mp4" -threads 0 -c:v vp9 -c:a libopus -b:a "128k" -vbr on -compression_level 10 -pix_fmt yuv420p -quality good -b:v "1280k" -crf 4 -vf "scale=trunc(480/2)_2:trunc(854/2)_2" -strict -2  "286971_480p.webm"

ffmpeg -i "286971.mp4" -vframes 1 -map 0:v:0 "286971.png"

convert 286971.png -quality 60 286971.jpg

direct into the shell, everything will be converted fine.

Any ideas?

Regards
Torsten

**Comment by flyser** [comment]
Thanks for the report!
The referenced commit should fix this issue. Unfortunately I can't test it right now, so please reopen if it persists.
